//! Hook points for testing concurrent scenarios at linearization points —
//! single-threaded via guards, or shared across threads via
//! `install_shared` (see [`define_sp!`](macro@define_sp)).
//!
//! The [`invoke!`](macro@invoke) macro compiles away to a no-op in production
//! builds (when `cfg(test)` is `false` on the consuming crate), so this crate
//! has zero cost in production builds.
//! Under loom (`cfg(test)` + `cfg(loom)`) the full infrastructure compiles
//! but hooks resolve to the default no-op impl — equivalent to production.

// --- Marker trait ---

/// Marker trait for sync-point implementations. Supertrait of the extension
/// traits generated by [`define_sp!`].
///
/// The `Send + Sync` supertraits let shared-mode guards (which carry a
/// `&dyn SyncPoint` back-reference to the previously installed sync point)
/// cross into worker threads.
pub trait SyncPoint: Send + Sync {}

// --- invoke! macro ---

/// Invoke the currently installed sync-point hook.
///
/// Expands to a real dispatch under `#[cfg(test)]` (evaluated at the call-site
/// crate's test mode), and to a no-op otherwise.
#[macro_export]
macro_rules! invoke {
    ($sp:path, $func:ident ( $($args:expr),* )) => {
        #[cfg(test)]
        {
            <$sp>::with_dyn(|__sp| __sp.$func($($args),*));
        }
    };
}

// --- trace_enabled ---

/// Check whether sync-point tracing is enabled via the `SP_TRACE` environment
/// variable. When set, every hook fire prints its name and call index to
/// stderr — useful for discovering expected sequences and call counts.
pub fn trace_enabled() -> bool {
    use std::sync::atomic::{AtomicU8, Ordering};
    // Tri-state: 0 = uninitialized, 1 = off, 2 = on. The environment is
    // process-global, so a racy double-initialization is benign (both
    // threads observe the same `SP_TRACE` value).
    static SP_TRACE: AtomicU8 = AtomicU8::new(0);
    let state = SP_TRACE.load(Ordering::Acquire);
    match state {
        0 => {
            let on = std::env::var_os("SP_TRACE").is_some();
            SP_TRACE.store(if on { 2 } else { 1 }, Ordering::Release);
            on
        }
        2 => true,
        _ => false,
    }
}

// --- HookId trait ---

/// Identity of a sync point hook, used for per-hook call accounting.
///
/// Implementations are generated by [`define_sp!`] alongside the hook enum.
/// The `id` discriminant is the hash-map key for per-hook counts; `name` is
/// shown in drop-time assertion failures.
pub trait HookId {
    #[must_use]
    fn id(&self) -> u64;
    #[must_use]
    fn name(&self) -> &'static str;
}

// --- Gate ---

/// A simple boolean gate for coordinating threads in concurrent tests.
///
/// Threads block in [`wait`](Self::wait) (or
/// [`must_wait`](Self::must_wait)) until another thread calls
/// [`set`](Self::set). Reusable: [`clear`](Self::clear) arms it for the
/// next wait.
///
/// The gate is panic-safe: a poisoned lock (a panicking waiter) is
/// transparently recovered via [`into_inner`](std::sync::PoisonError::into_inner).
#[derive(Debug)]
pub struct Gate {
    flag: std::sync::Mutex<bool>,
    cv: std::sync::Condvar,
}

impl Default for Gate {
    fn default() -> Self {
        Self::new()
    }
}

impl Gate {
    /// Create a new, unset gate.
    #[must_use]
    pub fn new() -> Self {
        Self {
            flag: std::sync::Mutex::new(false),
            cv: std::sync::Condvar::new(),
        }
    }

    /// Set the gate, waking every thread blocked in
    /// [`wait`](Self::wait) / [`wait_timeout`](Self::wait_timeout).
    pub fn set(&self) {
        let mut flag = self.flag.lock().unwrap_or_else(|e| e.into_inner());
        *flag = true;
        self.cv.notify_all();
    }

    /// Clear the gate so a subsequent [`wait`](Self::wait) blocks again.
    pub fn clear(&self) {
        *self.flag.lock().unwrap_or_else(|e| e.into_inner()) = false;
    }

    /// Whether the gate is currently set.
    #[must_use]
    pub fn is_set(&self) -> bool {
        *self.flag.lock().unwrap_or_else(|e| e.into_inner())
    }

    /// Block until the gate is set. May hang forever if the gate is never
    /// set — prefer [`must_wait`](Self::must_wait) where a hang would be
    /// indistinguishable from a test bug.
    pub fn wait(&self) {
        let mut flag = self.flag.lock().unwrap_or_else(|e| e.into_inner());
        while !*flag {
            flag = self.cv.wait(flag).unwrap_or_else(|e| e.into_inner());
        }
    }

    /// Block until the gate is set or `timeout` elapses. Returns `true` if
    /// the gate was set. Spurious condvar wakeups do not terminate the wait
    /// early: the condition is re-checked against a deadline.
    pub fn wait_timeout(&self, timeout: std::time::Duration) -> bool {
        let deadline = std::time::Instant::now() + timeout;
        let mut flag = self.flag.lock().unwrap_or_else(|e| e.into_inner());
        while !*flag {
            let now = std::time::Instant::now();
            if now >= deadline {
                return false;
            }
            let (guard, _) = self
                .cv
                .wait_timeout(flag, deadline - now)
                .unwrap_or_else(|e| e.into_inner());
            flag = guard;
        }
        true
    }

    /// Block until the gate is set, panicking with a timeout diagnostic if
    /// `timeout` elapses first. Prefer over [`wait`](Self::wait) inside
    /// sequence-step closures: a missed [`set`](Self::set) fails the test
    /// with a message instead of hanging it.
    pub fn must_wait(&self, timeout: std::time::Duration) {
        assert!(
            self.wait_timeout(timeout),
            "shadow-point: gate wait timed out after {timeout:?}"
        );
    }
}

// --- Fire info ---

/// Metadata about the hook fire currently being dispatched on this thread.
///
/// Returned by [`current_fire`] while a hook closure runs (fire-once, a
/// sequence step, or an `every` closure); `None` outside of any dispatch.
#[derive(Clone, Debug)]
pub struct FireInfo {
    /// Name of the hook being dispatched.
    pub hook: &'static str,
    /// Zero-based index of this fire on this hook (global across threads).
    pub index: usize,
    /// Id of the thread the hook fired on.
    pub thread_id: std::thread::ThreadId,
    /// Name of the thread the hook fired on, if set.
    pub thread_name: Option<String>,
}

// `const {}` would be the idiomatic modern form, but inline const blocks
// are experimental until 1.79 and the crate targets MSRV 1.65.
thread_local! {
    #[allow(clippy::missing_const_for_thread_local)]
    static CURRENT_FIRE: std::cell::RefCell<Option<FireInfo>> =
        std::cell::RefCell::new(None);
}

/// Metadata about the hook fire currently being dispatched on this thread,
/// or `None` outside of a hook dispatch (e.g. in the main thread before any
/// hook fired, or after a dispatch finished).
#[must_use]
pub fn current_fire() -> Option<FireInfo> {
    CURRENT_FIRE.with(|c| c.borrow().clone())
}

/// RAII guard that installs [`FireInfo`] as the current fire on this thread
/// and restores the previous value on drop (panic-safe and nesting-safe).
/// Hidden: used only from macro expansions generated by [`define_sp!`].
#[doc(hidden)]
#[must_use]
pub struct CurrentFire {
    prev: Option<FireInfo>,
}

impl CurrentFire {
    #[doc(hidden)]
    pub fn install(info: FireInfo) -> Self {
        let prev = CURRENT_FIRE.with(|c| c.borrow_mut().replace(info));
        Self { prev }
    }
}

impl Drop for CurrentFire {
    fn drop(&mut self) {
        CURRENT_FIRE.with(|c| *c.borrow_mut() = self.prev.take());
    }
}

// --- Timeouts ---

/// Maximum time a thread parks in shared mode while the sequence head is a
/// different hook. Parking is a mutual-deadlock guard, not a synchronization
/// mechanism: threads re-check the sequence after every wake and park only
/// as long as the head still blocks them. A timeout therefore means the
/// test's sequence can never advance (no thread will ever fire the head
/// hook) — failing is better than hanging.
pub const PARK_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(10);

// See CURRENT_FIRE: inline `const {}` blocks are experimental until 1.79.
thread_local! {
    // Addresses of `__Sp` instances currently dispatching a hook on this
    // thread. Per-thread: a genuinely concurrent fire from another thread is
    // never suppressed, and `contains` still gives per-sync-point re-entry
    // suppression that survives transitive nesting (A -> B -> A).
    #[allow(clippy::missing_const_for_thread_local)]
    static EXEC_STACK: std::cell::RefCell<Vec<*const ()>> =
        std::cell::RefCell::new(Vec::new());
}

/// Whether the sync point at `sp` is currently dispatching a hook on THIS
/// thread.
///
/// Re-entry suppression is per-thread and per-sync-point. A single
/// per-`__Sp` global atomic would also suppress legitimate fires from other
/// threads — including the very fire a parked thread is waiting for — so
/// the executing set lives in the thread.
#[doc(hidden)]
#[must_use]
pub fn __sp_executing(sp: *const ()) -> bool {
    EXEC_STACK.with(|s| s.borrow().contains(&sp))
}

/// RAII guard that marks a sync point as executing on this thread for the
/// duration of a hook dispatch (panic-safe). Hidden: used only from macro
/// expansions generated by [`define_sp!`].
#[doc(hidden)]
#[must_use]
pub struct ExecSink(*const ());

impl ExecSink {
    #[doc(hidden)]
    pub fn new(sp: *const ()) -> Self {
        EXEC_STACK.with(|s| s.borrow_mut().push(sp));
        Self(sp)
    }
}

impl Drop for ExecSink {
    fn drop(&mut self) {
        EXEC_STACK.with(|s| {
            let popped = s.borrow_mut().pop();
            // Dispatches on one thread are strictly nested (RAII), so the
            // top of the stack must be this dispatch's own entry.
            debug_assert_eq!(popped, Some(self.0), "ExecSink stack discipline violated");
        });
    }
}

// --- define_sp! macro ---

/// Generate a complete sync-point infrastructure from a prefix and hook list.
///
/// Given a `$prefix` like `Array`, generates:
///
/// - `trait {$prefix}SyncPoint` — extension trait with default (no-op) bodies
/// - `enum {$prefix}Hook` — hook identifiers with [`HookId`] impl
/// - `struct {$prefix}Sp` — entry point: `install_guard()`, `with_dyn()`,
///   and associated constants for each hook
/// - `struct {$prefix}SpGuard<T>` — guard with `Deref`, fire-once / sequence
///   / every registration, `expect_calls`, and `Drop` assertions
/// - `struct {$prefix}SeqBuilder<T>` — builder for `guard.sequence(...)`
/// - Internal: `__Sp<T>` (state), `__SpDefault`, `SeqEntry`, `EveryClosures`,
///   `EveryBuilder`, `SpExpect`, `__SP_TL` (thread-local)
///
/// # Specification syntax
///
/// ```text
/// define_sp! {
///     $vis prefix $prefix
///     {
///         $method($arg: $ty, ...),
///         ...
///     }
/// }
/// ```
///
/// # Example
///
/// ```ignore
/// define_sp! {
///     pub(in crate::core_array) prefix Array
///     {
///         entry_before_latch(path: &InsertHintsPath, found_idx: Option<BucketIndex>),
///         before_drain_latch(),
///     }
/// }
/// ```
#[macro_export]
macro_rules! define_sp {
    (
        $vis:vis prefix $prefix:ident
        {
            $( $method:ident ( $( $arg:ident : $arg_ty:ty ),* $(,)? ) ),+ $(,)?
        }
    ) => {
        ::paste::paste! {
            use $crate::HookId;

            // ── Extension trait ───────────────────────────────────────

            $vis trait [<$prefix SyncPoint>]: $crate::SyncPoint {
                $( fn $method(&self $( , _: $arg_ty)*) {} )+
            }

            // ── Default impl + thread-local ───────────────────────────

            struct __SpDefault;
            impl $crate::SyncPoint for __SpDefault {}
            impl [<$prefix SyncPoint>] for __SpDefault {}

            static __SP_DEFAULT: __SpDefault = __SpDefault;

            thread_local! {
                // Plain const-evaluable initializers: inline `const {}`
                // blocks (experimental until 1.79) would break MSRV 1.65.
                static __SP_TL: ::std::cell::Cell<
                    &'static dyn [<$prefix SyncPoint>]
                > = ::std::cell::Cell::new(
                    &__SP_DEFAULT as &'static dyn [<$prefix SyncPoint>]
                );
            }

            // ── Entry-point struct ────────────────────────────────────

            $vis struct [<$prefix Sp>];

            #[allow(non_upper_case_globals, dead_code)]
            impl [<$prefix Sp>] {
                /// Hook identifiers as associated constants.
                $(
                    $vis const $method: [<$prefix Hook>] = [<$prefix Hook>]::$method;
                )+

                /// Invoke a closure with the currently installed sync-point.
                /// Used by `invoke!`.
                #[inline]
                $vis fn with_dyn<R>(
                    __f: impl ::std::ops::FnOnce(&dyn [<$prefix SyncPoint>]) -> R,
                ) -> R {
                    __SP_TL.with(|__c| __f(__c.get()))
                }

                /// Install a guard that drives sync-point hooks for `value`.
                ///
                /// The guard derefs to `&T`, so test code can call `T`'s
                /// methods directly on it.
                #[track_caller]
                $vis fn install_guard<T: Send + Sync + 'static>(
                    value: T,
                ) -> [<$prefix SpGuard>]<T> {
                    [<$prefix SpGuard>]::install(value)
                }

                /// Share a sync point across threads, returning an `Arc`
                /// that drives hooks from any thread.
                ///
                /// Register `sequence`/`every`/`expect_calls`/fire-once on
                /// the returned value from the test thread, then have every
                /// worker install it on its own thread via
                /// `{$prefix}SharedSp::install()` before calling
                /// instrumented code. `invoke!` then dispatches into the
                /// shared state on the firing thread. Derefs to `&T`.
                ///
                /// # Caveats
                ///
                /// 1. A thread parked at the head of the sequence is inside
                ///    the instrumented code path and holds production locks.
                ///    Order the `sequence` entries so the head consumer
                ///    never needs a lock held by a parked thread — otherwise
                ///    that fire fails with a `sequence park timeout` panic,
                ///    not a hang.
                /// 2. `sequence` orders the *consumption* of entries, not
                ///    the completion of their closures: a later step may
                ///    finish before an earlier one. Coordinate completion
                ///    with [`Gate`](crate::Gate).
                /// 3. Fire-once closures are nondeterministic in shared
                ///    mode: the winner is whichever thread's call counter
                ///    lands first, and the closure receives that thread's
                ///    arguments. Use `sequence` for deterministic ordering.
                /// 4. Register `sequence`/`every`/`expect_calls` before
                ///    spawning workers; a fire that reaches the sync point
                ///    before registration silently falls through to
                ///    fire-once/counter.
                /// 5. Same-named entries from different threads are each
                ///    consumed exactly once (entries are re-checked after
                ///    every wake), but wake order is not FIFO.
                /// 6. Join all workers and drop every `{$prefix}SharedGuard`
                ///    before dropping the last `Arc`: the shared
                ///    assertions run on the final drop, and a worker still
                ///    parked at that point fails with a `sequence park
                ///    timeout` panic instead of being joined.
                /// 7. In shared mode, an `optional` entry at the head is
                ///    skipped — its closure never runs — when any *other*
                ///    hook fires while it is at the head. In private mode
                ///    the same mismatch leaves the entry in place, forgiven
                ///    at drop.
                #[track_caller]
                $vis fn install_shared<T: Send + Sync + 'static>(
                    value: T,
                ) -> ::std::sync::Arc<[<$prefix SharedSp>]<T>> {
                    let mut sp = Box::new(__Sp::new(
                        value,
                        std::panic::Location::caller(),
                    ));
                    // Read by dispatch without a lock; written here before
                    // the `Arc` is published to worker threads.
                    sp.shared = true;
                    ::std::sync::Arc::new([<$prefix SharedSp>] {
                        sp: Box::leak(sp),
                    })
                }
            }

            // ── Hook enum ─────────────────────────────────────────────

            #[repr(u64)]
            #[derive(Debug, Clone, Copy, PartialEq, Eq)]
            #[allow(non_camel_case_types, dead_code)]
            $vis enum [<$prefix Hook>] {
                $( $method, )+
            }

            impl $crate::HookId for [<$prefix Hook>] {
                #[inline]
                fn id(&self) -> u64 {
                    *self as u64
                }
                fn name(&self) -> &'static str {
                    match self {
                        $( [<$prefix Hook>]::$method => stringify!($method), )+
                    }
                }
            }

            // ── Sequence entry ────────────────────────────────────────

            #[allow(non_camel_case_types, dead_code)]
            enum SeqEntry<T: Send + Sync + 'static> {
                // Each entry carries an optional predicate over the hook
                // arguments and an `optional` flag. `None` predicate (the
                // default from `$method(f)`) consumes unconditionally on the
                // next matching fire; `Some(pred)` (from
                // `$method_when(pred, f)`) consumes only when `pred(&args)`
                // passes, otherwise the entry stays at the front of the
                // sequence and waits for the next fire. Useful when a hook
                // fires for several distinct scenarios (e.g. a retry probe
                // vs. a real attempt) and only some should advance the step.
                // The flag (set via `SeqBuilder::optional`) marks entries
                // that may legitimately remain unconsumed at guard drop
                // (e.g. a trailing sentinel); every other entry — gated or
                // not — must fire. Closures are `Send`: shared-mode entries
                // cross into engine threads.
                $( $method(
                    Option<Box<dyn Fn($($arg_ty),*) -> bool + Send>>,
                    Box<dyn FnOnce(&T $( , $arg_ty)*) + Send>,
                    bool,
                ), )+
            }

            #[allow(dead_code)]
            impl<T: Send + Sync + 'static> SeqEntry<T> {
                fn matches(&self, hook: [<$prefix Hook>]) -> bool {
                    matches!(
                        (self, hook),
                        $( (Self::$method(..), [<$prefix Hook>]::$method) ) | +
                    )
                }
                fn name(&self) -> &'static str {
                    match self {
                        $( Self::$method(..) => stringify!($method), )+
                    }
                }
                /// Whether this entry may legitimately remain unconsumed at
                /// guard drop (marked via `SeqBuilder::optional`, e.g. a
                /// trailing sentinel). Every other entry — gated or not —
                /// must fire.
                fn is_optional(&self) -> bool {
                    match self {
                        $( Self::$method(_, _, optional) => *optional, )+
                    }
                }
                fn set_optional(&mut self, optional: bool) {
                    match self {
                        $( Self::$method(_, _, opt) => *opt = optional, )+
                    }
                }
            }

            // ── Every-fire closures ───────────────────────────────────

            // `Arc` so a dispatch clones the closure under the lock and
            // calls it after unlocking: concurrent dispatches on different
            // threads never serialize on each other's `every` closures.
            #[allow(dead_code)]
            struct EveryClosures<T: Send + Sync + 'static> {
                $( $method: Option<
                    ::std::sync::Arc<dyn Fn(&T $( , $arg_ty)*) + Send + Sync>
                >, )+
            }

            // ── Sync-point state ──────────────────────────────────────

            // Per-field `Mutex`: a thread parked on `sequence` never blocks
            // `calls`/`every`/fire-once slots, and different threads
            // register and fire concurrently. `shared` is written once
            // before the sync point is published to worker threads (read by
            // dispatch without a lock); `installed_at` is the
            // `#[track_caller]` site. All locks are recovered from poison
            // via `PoisonError::into_inner`: a park-timeout panic poisons
            // the sequence mutex, and other threads must keep running to
            // report their own diagnostics.
            #[allow(dead_code)]
            struct __Sp<T: Send + Sync + 'static> {
                value: T,
                $(
                    $method: ::std::sync::Mutex<
                        Option<Box<dyn FnOnce(&T $( , $arg_ty)*) + Send>>
                    >,
                )+
                every: ::std::sync::Mutex<EveryClosures<T>>,
                sequence: ::std::sync::Mutex<
                    ::std::collections::VecDeque<SeqEntry<T>>
                >,
                sequence_cv: ::std::sync::Condvar,
                shared: bool,
                installed_at: &'static std::panic::Location<'static>,
                calls: ::std::sync::Mutex<
                    ::std::collections::HashMap<u64, (&'static str, usize)>
                >,
                expected: ::std::sync::Mutex<
                    ::std::collections::HashMap<u64, (&'static str, usize)>
                >,
            }

            #[allow(dead_code)]
            impl<T: Send + Sync + 'static> __Sp<T> {
                fn new(
                    value: T,
                    installed_at: &'static std::panic::Location<'static>,
                ) -> Self {
                    Self {
                        value,
                        $( $method: ::std::sync::Mutex::new(None), )+
                        every: ::std::sync::Mutex::new(EveryClosures {
                            $( $method: None, )+
                        }),
                        sequence: ::std::sync::Mutex::new(
                            ::std::collections::VecDeque::new()
                        ),
                        sequence_cv: ::std::sync::Condvar::new(),
                        shared: false,
                        installed_at,
                        calls: ::std::sync::Mutex::new(
                            ::std::collections::HashMap::new()
                        ),
                        expected: ::std::sync::Mutex::new(
                            ::std::collections::HashMap::new()
                        ),
                    }
                }

                fn bump_call(&self, hook: [<$prefix Hook>]) -> usize {
                    let mut calls = self
                        .calls
                        .lock()
                        .unwrap_or_else(|e| e.into_inner());
                    let entry = calls.entry(hook.id()).or_insert((hook.name(), 0));
                    let idx = entry.1;
                    entry.1 += 1;
                    idx
                }

                fn set_expected(&self, hook: [<$prefix Hook>], n: usize) {
                    self.expected
                        .lock()
                        .unwrap_or_else(|e| e.into_inner())
                        .insert(hook.id(), (hook.name(), n));
                }
            }

            impl<T: Send + Sync + 'static> $crate::SyncPoint for __Sp<T> {}

            impl<T: Send + Sync + 'static> [<$prefix SyncPoint>] for __Sp<T> {
                $(
                    fn $method(&self $( , $arg: $arg_ty)*) {
                        // Re-entry suppression is per-thread and
                        // per-sync-point (see `__sp_executing`): a nested
                        // dispatch of any hook of this sync point from the
                        // same thread is dropped before it counts or
                        // consumes, while a genuinely concurrent fire from
                        // another thread always proceeds — including the
                        // fire that unblocks a parked thread.
                        let __sp_addr = self as *const Self as *const ();
                        if $crate::__sp_executing(__sp_addr) {
                            return;
                        }
                        let _e = $crate::ExecSink::new(__sp_addr);
                        let __hook = [<$prefix Hook>]::$method;
                        let __idx = self.bump_call(__hook);
                        if $crate::trace_enabled() {
                            eprintln!(
                                "[sp] {} call #{} thread={}",
                                __hook.name(),
                                __idx + 1,
                                std::thread::current()
                                    .name()
                                    .unwrap_or("<unnamed>"),
                            );
                        }
                        let _f = $crate::CurrentFire::install($crate::FireInfo {
                            hook: __hook.name(),
                            index: __idx,
                            thread_id: std::thread::current().id(),
                            thread_name: std::thread::current()
                                .name()
                                .map(|n| n.to_owned()),
                        });
                        // `every`: clone the `Arc` under the lock, then call
                        // unlocked so concurrent dispatches don't serialize.
                        let __every = {
                            let guard = self
                                .every
                                .lock()
                                .unwrap_or_else(|e| e.into_inner());
                            guard.$method.clone()
                        };
                        if let Some(__f) = __every {
                            __f(&self.value $( , $arg)*);
                        }
                        // Sequence: peek the front entry. Four cases:
                        //   * front expects this hook and predicate passes
                        //     (or there is none) -> consume: pop + wake +
                        //     run, wake strictly before the step so a woken
                        //     thread never waits for the step to finish.
                        //   * front expects this hook but predicate fails ->
                        //     leave it in place and wait for a fire whose
                        //     args pass; this fire is dropped and fire-once
                        //     is NOT triggered (the entry is still pending).
                        //   * shared mode, front is a DIFFERENT hook marked
                        //     optional -> skip it and continue (private mode
                        //     never skips optional entries).
                        //   * front is a different mandatory hook -> if a
                        //     later entry matches this hook: private mode
                        //     panics (ordering violation), shared mode parks
                        //     on `sequence_cv` and re-checks after every
                        //     wake (no FIFO). If no later entry matches,
                        //     fall through to fire-once on the first call.
                        let (__head_expects_this_hook, __consumed) = {
                            let mut __seq = self
                                .sequence
                                .lock()
                                .unwrap_or_else(|e| e.into_inner());
                            // Becomes true when a park times out; the panic
                            // fires only if the re-derived head STILL blocks
                            // this hook (see the shared park arm below).
                            let mut __timed_out_last = false;
                            loop {
                                match __seq.front() {
                                    None => break (false, None),
                                    Some(__front) if __front.matches(__hook) => {
                                        let __pass = match __front {
                                            SeqEntry::$method(Some(__pred), _, _) => {
                                                __pred($($arg),*)
                                            }
                                            SeqEntry::$method(None, _, _) => true,
                                            // Unreachable: `matches` already
                                            // confirmed this variant.
                                            _ => true,
                                        };
                                        if __pass {
                                            let __entry = __seq.pop_front();
                                            self.sequence_cv.notify_all();
                                            break (true, __entry);
                                        }
                                        break (true, None);
                                    }
                                    Some(__front)
                                        if self.shared && __front.is_optional() =>
                                    {
                                        __seq.pop_front();
                                        self.sequence_cv.notify_all();
                                        continue;
                                    }
                                    Some(__front) => {
                                        let __has_more = __seq
                                            .iter()
                                            .any(|e| e.matches(__hook));
                                        if !__has_more {
                                            break (false, None);
                                        }
                                        if self.shared {
                                            // Timeout panic only when the head
                                            // STILL does not match: the head may
                                            // have advanced (pop + notify_all)
                                            // between this thread's deadline
                                            // expiring and its re-acquisition of
                                            // the sequence mutex — a raced
                                            // timeout must re-check, not panic
                                            // on a stale condition.
                                            if __timed_out_last {
                                                panic!(
                                                    "shadow-point: sequence park \
                                                     timeout ({:?}): thread waiting \
                                                     for `{}`, head is `{}` \
                                                     (installed at {})",
                                                    $crate::PARK_TIMEOUT,
                                                    __hook.name(),
                                                    __front.name(),
                                                    self.installed_at,
                                                );
                                            }
                                            let (__g, __w) = self
                                                .sequence_cv
                                                .wait_timeout(
                                                    __seq,
                                                    $crate::PARK_TIMEOUT,
                                                )
                                                .unwrap_or_else(|e| e.into_inner());
                                            __seq = __g;
                                            __timed_out_last = __w.timed_out();
                                            continue;
                                        }
                                        panic!(
                                            "sync point ordering violation: \
                                             expected `{}` next but `{}` fired",
                                            __front.name(),
                                            __hook.name()
                                        );
                                    }
                                }
                            }
                        };
                        match __consumed {
                            Some(SeqEntry::$method(_, __f, _)) => {
                                __f(&self.value $( , $arg)*);
                            }
                            // The sequence loop only pops entries that match
                            // this hook, so no other variant can be consumed.
                            Some(_) => unreachable!(
                                "shadow-point: consumed a non-matching sequence entry"
                            ),
                            None => {
                                if __idx == 0 && !__head_expects_this_hook {
                                    let __fire_once = {
                                        let mut __slot = self
                                            .$method
                                            .lock()
                                            .unwrap_or_else(|e| e.into_inner());
                                        __slot.take()
                                    };
                                    if let Some(__f) = __fire_once {
                                        __f(&self.value $( , $arg)*);
                                    }
                                }
                            }
                        }
                    }
                )+
            }

            // ── Sequence builder ──────────────────────────────────────

            #[allow(dead_code)]
            $vis struct [<$prefix SeqBuilder>]<T: Send + Sync + 'static> {
                seq: ::std::collections::VecDeque<SeqEntry<T>>,
            }

            #[allow(dead_code)]
            impl<T: Send + Sync + 'static> [<$prefix SeqBuilder>]<T> {
                $(
                    /// Push a sequence entry for this hook.
                    ///
                    /// The entry consumes unconditionally on the next matching
                    /// fire. For a predicate-gated variant see the
                    /// `<$method>_when` builder method.
                    $vis fn $method(
                        &mut self,
                        f: impl FnOnce(&T $( , $arg_ty)*) + Send + 'static,
                    ) -> &mut Self {
                        self.seq
                            .push_back(SeqEntry::$method(None, Box::new(f), false));
                        self
                    }

                    /// Push a predicate-gated sequence entry for this hook.
                    ///
                    /// The entry stays at the front of the sequence until a fire
                    /// of this hook whose arguments pass `pred`, then consumes
                    /// and runs `f`. Fires that fail `pred` leave the entry in
                    /// place. Useful when a hook fires for several distinct
                    /// scenarios (e.g. a real attempt vs. a retry probe) and
                    /// only some should advance the step.
                    ///
                    /// A gated entry must still be consumed: if it is left at
                    /// the front at guard drop, the drop assertion fails. Chain
                    /// [`optional`](Self::optional) if the entry may
                    /// legitimately never fire (e.g. a trailing sentinel).
                    ///
                    /// `pred` runs while the sequence lock is held: it must
                    /// be pure — no hook invocations and no blocking.
                    $vis fn [< $method _when >](
                        &mut self,
                        pred: impl Fn($($arg_ty),*) -> bool + Send + 'static,
                        f: impl FnOnce(&T $( , $arg_ty)*) + Send + 'static,
                    ) -> &mut Self {
                        self.seq.push_back(SeqEntry::$method(
                            Some(Box::new(pred)),
                            Box::new(f),
                            false,
                        ));
                        self
                    }
                )+

                /// Mark the most recently pushed entry as optional: it may
                /// legitimately remain unconsumed at guard drop (its hook
                /// never fired, or its predicate never passed). Typical use
                /// is a trailing sentinel that must panic only on an
                /// unexpected extra fire.
                ///
                /// Panics if no entries have been pushed yet.
                $vis fn optional(&mut self) -> &mut Self {
                    self.seq
                        .back_mut()
                        .expect("SeqBuilder::optional called with no entries")
                        .set_optional(true);
                    self
                }
            }

            // ── Every builder ─────────────────────────────────────────

            #[allow(dead_code)]
            $vis struct EveryBuilder<T: Send + Sync + 'static> {
                every: EveryClosures<T>,
            }

            #[allow(dead_code)]
            impl<T: Send + Sync + 'static> EveryBuilder<T> {
                $(
                    /// Register a closure that fires on every invocation of
                    /// this hook (on the firing thread, after the state
                    /// locks are released).
                    #[allow(clippy::type_complexity)]
                    $vis fn $method(
                        &mut self,
                        f: impl Fn(&T $( , $arg_ty)*) + Send + Sync + 'static,
                    ) -> &mut Self {
                        self.every.$method = Some(::std::sync::Arc::new(f));
                        self
                    }
                )+
            }

            // ── Fire-once fluent helper ───────────────────────────────

            #[allow(dead_code)]
            $vis struct SpExpect<'a, T: Send + Sync + 'static> {
                sp: &'a __Sp<T>,
                hook: [<$prefix Hook>],
            }

            #[allow(dead_code)]
            impl<T: Send + Sync + 'static> SpExpect<'_, T> {
                /// Assert that the hook fires exactly `n` times.
                $vis fn expect(self, n: usize) {
                    self.sp.set_expected(self.hook, n);
                }
            }

            // ── Guard ─────────────────────────────────────────────────

            /// Guard returned by `{$prefix}Sp::install_guard()`.
            ///
            /// Derefs to the guarded value. Drop asserts that all registered
            /// sequences were consumed and all `expect_calls` counts match.
            ///
            /// Drop the guard on the thread that installed it: the guard
            /// restores the previously installed sync point of ITS OWN thread
            /// (TLS). Moving a guard across threads and dropping it there
            /// silently clobbers the destination thread's pointer.
            #[clippy::has_significant_drop]
            #[must_use]
            $vis struct [<$prefix SpGuard>]<T: Send + Sync + 'static> {
                sp: &'static __Sp<T>,
                old: &'static dyn [<$prefix SyncPoint>],
            }

            #[allow(dead_code)]
            impl<T: Send + Sync + 'static> [<$prefix SpGuard>]<T> {
                #[track_caller]
                fn install(value: T) -> Self {
                    let sp: &'static __Sp<T> = Box::leak(Box::new(
                        __Sp::new(value, std::panic::Location::caller()),
                    ));
                    let old = __SP_TL.with(|__c| __c.replace(sp));
                    Self { sp, old }
                }

                $(
                    /// Register a fire-once closure for this hook.
                    ///
                    /// The closure runs on the first invocation. Chain
                    /// `.expect(n)` to assert a specific call count, or drop
                    /// the return for an unconditional one-shot.
                    $vis fn $method(
                        &self,
                        f: impl FnOnce(&T $( , $arg_ty)*) + Send + 'static,
                    ) -> SpExpect<'_, T> {
                        *self
                            .sp
                            .$method
                            .lock()
                            .unwrap_or_else(|e| e.into_inner()) = Some(Box::new(f));
                        SpExpect {
                            sp: self.sp,
                            hook: [<$prefix Hook>]::$method,
                        }
                    }
                )+

                /// Register an ordered sequence of hook fires.
                ///
                /// Each builder method pushes a closure that must fire in
                /// registration order. Out-of-order fires panic.
                $vis fn sequence(&self, f: impl FnOnce(&mut [<$prefix SeqBuilder>]<T>)) {
                    let mut builder = [<$prefix SeqBuilder>] {
                        seq: ::std::collections::VecDeque::new(),
                    };
                    f(&mut builder);
                    *self
                        .sp
                        .sequence
                        .lock()
                        .unwrap_or_else(|e| e.into_inner()) = builder.seq;
                }

                /// Register closures that fire on every invocation.
                $vis fn every(&self, f: impl FnOnce(&mut EveryBuilder<T>)) {
                    let mut builder = EveryBuilder {
                        every: EveryClosures {
                            $( $method: None, )+
                        },
                    };
                    f(&mut builder);
                    *self
                        .sp
                        .every
                        .lock()
                        .unwrap_or_else(|e| e.into_inner()) = builder.every;
                }

                /// Assert that `hook` fires exactly `n` times before drop.
                $vis fn expect_calls(&self, hook: [<$prefix Hook>], n: usize) {
                    self.sp.set_expected(hook, n);
                }
            }

            impl<T: Send + Sync + 'static> std::ops::Deref for [<$prefix SpGuard>]<T> {
                type Target = T;
                fn deref(&self) -> &T {
                    &self.sp.value
                }
            }

            impl<T: Send + Sync + 'static> Drop for [<$prefix SpGuard>]<T> {
                fn drop(&mut self) {
                    __SP_TL.with(|__c| __c.set(self.old));

                    let seq = self.sp.sequence.lock().unwrap_or_else(|e| e.into_inner());
                    // Entries marked optional via `SeqBuilder::optional`
                    // (e.g. a trailing sentinel) may remain unconsumed:
                    // their hook never fired, or their predicate never
                    // passed. Every other entry — gated or not — must have
                    // fired; any remaining is a missing scenario step.
                    let unconsumed: Vec<_> =
                        seq.iter().filter(|e| !e.is_optional()).collect();
                    assert!(
                        unconsumed.is_empty(),
                        "sync point sequence not fully consumed: \
                         {} entr{} remaining [{}] (installed at {})",
                        unconsumed.len(),
                        if unconsumed.len() == 1 { "y" } else { "ies" },
                        unconsumed
                            .iter()
                            .map(|e| e.name())
                            .collect::<Vec<_>>()
                            .join(", "),
                        self.sp.installed_at,
                    );
                    drop(seq);

                    let expected = self
                        .sp
                        .expected
                        .lock()
                        .unwrap_or_else(|e| e.into_inner());
                    let calls = self.sp.calls.lock().unwrap_or_else(|e| e.into_inner());
                    for (id, (name, expected)) in expected.iter() {
                        let actual = calls.get(id).map_or(0, |(_, c)| *c);
                        assert_eq!(
                            actual, *expected,
                            "sync point hook `{name}` fired {actual} \
                             time(s), expected {expected} (installed at {})",
                            self.sp.installed_at,
                        );
                    }
                }
            }

            // ── Shared (cross-thread) state ───────────────────────────

            /// Sync point shared across threads, returned by
            /// `{$prefix}Sp::install_shared()`.
            ///
            /// Register `sequence`/`every`/fire-once/`expect_calls` from the
            /// test thread before spawning workers, then call
            /// [`install`](Self::install) in every worker that must drive
            /// the hooks. Derefs to the shared value. Drop (of the last
            /// `Arc` clone) asserts that all registered sequences were
            /// consumed and all `expect_calls` counts match — same
            /// assertions as `{$prefix}SpGuard`.
            #[clippy::has_significant_drop]
            #[must_use]
            $vis struct [<$prefix SharedSp>]<T: Send + Sync + 'static> {
                sp: &'static __Sp<T>,
            }

            #[allow(dead_code)]
            impl<T: Send + Sync + 'static> [<$prefix SharedSp>]<T> {
                $(
                    /// Register a fire-once closure for this hook.
                    ///
                    /// In shared mode the closure is nondeterministic: the
                    /// winner is whichever thread's call counter lands
                    /// first, and the closure receives that thread's
                    /// arguments. Use `sequence` for deterministic
                    /// ordering.
                    $vis fn $method(
                        &self,
                        f: impl FnOnce(&T $( , $arg_ty)*) + Send + 'static,
                    ) -> SpExpect<'_, T> {
                        *self
                            .sp
                            .$method
                            .lock()
                            .unwrap_or_else(|e| e.into_inner()) = Some(Box::new(f));
                        SpExpect {
                            sp: self.sp,
                            hook: [<$prefix Hook>]::$method,
                        }
                    }
                )+

                /// Register an ordered sequence of hook fires across
                /// threads. See `{$prefix}SpGuard::sequence`.
                $vis fn sequence(&self, f: impl FnOnce(&mut [<$prefix SeqBuilder>]<T>)) {
                    let mut builder = [<$prefix SeqBuilder>] {
                        seq: ::std::collections::VecDeque::new(),
                    };
                    f(&mut builder);
                    *self
                        .sp
                        .sequence
                        .lock()
                        .unwrap_or_else(|e| e.into_inner()) = builder.seq;
                }

                /// Register closures that fire on every invocation (on the
                /// firing thread, after the state locks are released).
                $vis fn every(&self, f: impl FnOnce(&mut EveryBuilder<T>)) {
                    let mut builder = EveryBuilder {
                        every: EveryClosures {
                            $( $method: None, )+
                        },
                    };
                    f(&mut builder);
                    *self
                        .sp
                        .every
                        .lock()
                        .unwrap_or_else(|e| e.into_inner()) = builder.every;
                }

                /// Assert that `hook` fires exactly `n` times in total
                /// before the last `Arc` clone is dropped.
                $vis fn expect_calls(&self, hook: [<$prefix Hook>], n: usize) {
                    self.sp.set_expected(hook, n);
                }

                /// Install this sync point on the calling thread (TLS), so
                /// `invoke!` on that thread dispatches into the shared
                /// state; restores the previous sync point on drop.
                ///
                /// Call it from the thread that will drive the hooks — a
                /// worker must install its own guard inside the worker
                /// closure (TLS is per-thread; the guard carries the TLS
                /// restore for the thread it was created on, so drop the
                /// guard on the thread that installed it — never move it
                /// across threads). The returned
                /// guard owns an `Arc` clone of this sync point: the
                /// `SharedSp::drop` assertions run only after every worker
                /// has dropped its guard, so the final counts/sequence
                /// reads are race-free.
                $vis fn install(
                    self: &::std::sync::Arc<Self>,
                ) -> [<$prefix SharedGuard>]<T> {
                    let old = __SP_TL.with(|__c| __c.replace(self.sp));
                    [<$prefix SharedGuard>] {
                        _shared: ::std::sync::Arc::clone(self),
                        old,
                    }
                }
            }

            impl<T: Send + Sync + 'static> std::ops::Deref for [<$prefix SharedSp>]<T> {
                type Target = T;
                fn deref(&self) -> &T {
                    &self.sp.value
                }
            }

            impl<T: Send + Sync + 'static> Drop for [<$prefix SharedSp>]<T> {
                fn drop(&mut self) {
                    let seq = self.sp.sequence.lock().unwrap_or_else(|e| e.into_inner());
                    // Same assertions as `{$prefix}SpGuard::drop`, with the
                    // source marked "shared": `install_shared` state is
                    // dropped via the last `Arc`, not via a guard.
                    let unconsumed: Vec<_> =
                        seq.iter().filter(|e| !e.is_optional()).collect();
                    assert!(
                        unconsumed.is_empty(),
                        "sync point sequence not fully consumed: \
                         {} entr{} remaining [{}] (shared, installed at {})",
                        unconsumed.len(),
                        if unconsumed.len() == 1 { "y" } else { "ies" },
                        unconsumed
                            .iter()
                            .map(|e| e.name())
                            .collect::<Vec<_>>()
                            .join(", "),
                        self.sp.installed_at,
                    );
                    drop(seq);

                    let expected = self
                        .sp
                        .expected
                        .lock()
                        .unwrap_or_else(|e| e.into_inner());
                    let calls = self.sp.calls.lock().unwrap_or_else(|e| e.into_inner());
                    for (id, (name, expected)) in expected.iter() {
                        let actual = calls.get(id).map_or(0, |(_, c)| *c);
                        assert_eq!(
                            actual, *expected,
                            "sync point hook `{name}` fired {actual} \
                             time(s), expected {expected} (shared, installed at {})",
                            self.sp.installed_at,
                        );
                    }
                }
            }

            /// RAII TLS install of a shared sync point. Owns an `Arc` clone
            /// so the shared state and its drop assertions outlive every
            /// worker that installed it.
            #[clippy::has_significant_drop]
            #[must_use]
            $vis struct [<$prefix SharedGuard>]<T: Send + Sync + 'static> {
                _shared: ::std::sync::Arc<[<$prefix SharedSp>]<T>>,
                old: &'static dyn [<$prefix SyncPoint>],
            }

            impl<T: Send + Sync + 'static> Drop for [<$prefix SharedGuard>]<T> {
                fn drop(&mut self) {
                    __SP_TL.with(|__c| __c.set(self.old));
                }
            }
        }
    };
}
