//! Synchronization points for testing concurrent scenarios at linearization
//! points.
//!
//! The [`invoke!`](macro@invoke) macro compiles away to a no-op in production
//! builds (when `cfg(test)` is `false` on the consuming crate), so this crate
//! has zero cost in production builds.
//! Under loom (`cfg(test)` + `cfg(loom)`) the full infrastructure compiles
//! but hooks resolve to the default no-op impl — equivalent to production.

// --- Marker trait ---

/// Marker trait for sync-point implementations. Supertrait of the extension
/// traits generated by [`define_sp!`].
pub trait SyncPoint {}

// --- invoke! macro ---

/// Invoke the currently installed sync-point hook.
///
/// Expands to a real dispatch under `#[cfg(test)]` (evaluated at the call-site
/// crate's test mode), and to a no-op otherwise.
#[macro_export]
macro_rules! invoke {
    ($sp:path, $func:ident ( $($args:expr),* )) => {
        #[cfg(test)]
        {
            <$sp>::with_dyn(|__sp| __sp.$func($($args),*));
        }
    };
}

// --- trace_enabled ---

/// Check whether sync-point tracing is enabled via the `SP_TRACE` environment
/// variable. When set, every hook fire prints its name and call index to
/// stderr — useful for discovering expected sequences and call counts.
pub fn trace_enabled() -> bool {
    use std::sync::OnceLock;
    static FLAG: OnceLock<bool> = OnceLock::new();
    *FLAG.get_or_init(|| std::env::var_os("SP_TRACE").is_some())
}

// --- HookId trait ---

/// Identity of a sync point hook, used for per-hook call accounting.
///
/// Implementations are generated by [`define_sp!`] alongside the hook enum.
/// The `id` discriminant is the hash-map key for per-hook counts; `name` is
/// shown in drop-time assertion failures.
pub trait HookId {
    #[must_use]
    fn id(&self) -> u64;
    #[must_use]
    fn name(&self) -> &'static str;
}

// --- define_sp! macro ---

/// Generate a complete sync-point infrastructure from a prefix and hook list.
///
/// Given a `$prefix` like `Array`, generates:
///
/// - `trait {$prefix}SyncPoint` — extension trait with default (no-op) bodies
/// - `enum {$prefix}Hook` — hook identifiers with [`HookId`] impl
/// - `struct {$prefix}Sp` — entry point: `install_guard()`, `with_dyn()`,
///   and associated constants for each hook
/// - `struct {$prefix}SpGuard<T>` — guard with `Deref`, fire-once / sequence
///   / every registration, `expect_calls`, and `Drop` assertions
/// - `struct {$prefix}SeqBuilder<T>` — builder for `guard.sequence(...)`
/// - Internal: `__Sp<T>` (state), `__SpDefault`, `SeqEntry`, `EveryClosures`,
///   `EveryBuilder`, `SpExpect`, `__SP_TL` (thread-local)
///
/// # Specification syntax
///
/// ```text
/// define_sp! {
///     $vis prefix $prefix
///     {
///         $method($arg: $ty, ...),
///         ...
///     }
/// }
/// ```
///
/// # Example
///
/// ```ignore
/// define_sp! {
///     pub(in crate::core_array) prefix Array
///     {
///         entry_before_latch(path: &InsertHintsPath, found_idx: Option<BucketIndex>),
///         before_drain_latch(),
///     }
/// }
/// ```
#[macro_export]
macro_rules! define_sp {
    (
        $vis:vis prefix $prefix:ident
        {
            $( $method:ident ( $( $arg:ident : $arg_ty:ty ),* $(,)? ) ),+ $(,)?
        }
    ) => {
        ::paste::paste! {
            use $crate::HookId;

            // ── Extension trait ───────────────────────────────────────

            $vis trait [<$prefix SyncPoint>]: $crate::SyncPoint {
                $( fn $method(&self $( , _: $arg_ty)*) {} )+
            }

            // ── Default impl + thread-local ───────────────────────────

            struct __SpDefault;
            impl $crate::SyncPoint for __SpDefault {}
            impl [<$prefix SyncPoint>] for __SpDefault {}

            static __SP_DEFAULT: __SpDefault = const { __SpDefault };

            thread_local! {
                static __SP_TL: ::std::cell::Cell<
                    &'static dyn [<$prefix SyncPoint>]
                > = const {
                    ::std::cell::Cell::new(
                        &__SP_DEFAULT as &'static dyn [<$prefix SyncPoint>]
                    )
                };
            }

            // ── Entry-point struct ────────────────────────────────────

            $vis struct [<$prefix Sp>];

            #[allow(non_upper_case_globals, dead_code)]
            impl [<$prefix Sp>] {
                /// Hook identifiers as associated constants.
                $(
                    $vis const $method: [<$prefix Hook>] = [<$prefix Hook>]::$method;
                )+

                /// Invoke a closure with the currently installed sync-point.
                /// Used by `invoke!`.
                #[inline]
                $vis fn with_dyn<R>(
                    __f: impl ::std::ops::FnOnce(&dyn [<$prefix SyncPoint>]) -> R,
                ) -> R {
                    __SP_TL.with(|__c| __f(__c.get()))
                }

                /// Install a guard that drives sync-point hooks for `value`.
                ///
                /// The guard derefs to `&T`, so test code can call `T`'s
                /// methods directly on it.
                #[track_caller]
                $vis fn install_guard<T: 'static>(
                    value: T,
                ) -> [<$prefix SpGuard>]<T> {
                    [<$prefix SpGuard>]::install(value)
                }
            }

            // ── Hook enum ─────────────────────────────────────────────

            #[repr(u64)]
            #[derive(Debug, Clone, Copy, PartialEq, Eq)]
            #[allow(non_camel_case_types, dead_code)]
            $vis enum [<$prefix Hook>] {
                $( $method, )+
            }

            impl $crate::HookId for [<$prefix Hook>] {
                #[inline]
                fn id(&self) -> u64 {
                    *self as u64
                }
                fn name(&self) -> &'static str {
                    match self {
                        $( [<$prefix Hook>]::$method => stringify!($method), )+
                    }
                }
            }

            // ── Sequence entry ────────────────────────────────────────

            #[allow(non_camel_case_types, dead_code)]
            enum SeqEntry<T: 'static> {
                // Each entry carries an optional predicate over the hook
                // arguments and an `optional` flag. `None` predicate (the
                // default from `$method(f)`) consumes unconditionally on the
                // next matching fire; `Some(pred)` (from
                // `$method_when(pred, f)`) consumes only when `pred(&args)`
                // passes, otherwise the entry stays at the front of the
                // sequence and waits for the next fire. Useful when a hook
                // fires for several distinct scenarios (e.g. a retry probe
                // vs. a real attempt) and only some should advance the step.
                // The flag (set via `SeqBuilder::optional`) marks entries
                // that may legitimately remain unconsumed at guard drop
                // (e.g. a trailing sentinel); every other entry — gated or
                // not — must fire.
                $( $method(
                    Option<Box<dyn Fn($($arg_ty),*) -> bool>>,
                    Box<dyn FnOnce(&T $( , $arg_ty)*)>,
                    bool,
                ), )+
            }

            #[allow(dead_code)]
            impl<T: 'static> SeqEntry<T> {
                fn matches(&self, hook: [<$prefix Hook>]) -> bool {
                    matches!(
                        (self, hook),
                        $( (Self::$method(..), [<$prefix Hook>]::$method) ) | +
                    )
                }
                fn name(&self) -> &'static str {
                    match self {
                        $( Self::$method(..) => stringify!($method), )+
                    }
                }
                /// Whether this entry may legitimately remain unconsumed at
                /// guard drop (marked via `SeqBuilder::optional`, e.g. a
                /// trailing sentinel). Every other entry — gated or not —
                /// must fire.
                fn is_optional(&self) -> bool {
                    match self {
                        $( Self::$method(_, _, optional) => *optional, )+
                    }
                }
                fn set_optional(&mut self, optional: bool) {
                    match self {
                        $( Self::$method(_, _, opt) => *opt = optional, )+
                    }
                }
            }

            // ── Every-fire closures ───────────────────────────────────

            #[allow(dead_code)]
            struct EveryClosures<T: 'static> {
                $( $method: Option<Box<dyn Fn(&T $( , $arg_ty)*)>>, )+
            }

            // ── Sync-point state ──────────────────────────────────────

            #[allow(dead_code)]
            struct __Sp<T: 'static> {
                value: T,
                $(
                    $method: ::std::cell::RefCell<
                        Option<Box<dyn FnOnce(&T $( , $arg_ty)*)>>
                    >,
                )+
                every: ::std::cell::RefCell<EveryClosures<T>>,
                sequence: ::std::cell::RefCell<
                    ::std::collections::VecDeque<SeqEntry<T>>
                >,
                executing: ::std::cell::Cell<bool>,
                calls: ::std::cell::RefCell<
                    ::std::collections::HashMap<u64, (&'static str, usize)>
                >,
                expected: ::std::cell::RefCell<
                    ::std::collections::HashMap<u64, (&'static str, usize)>
                >,
            }

            #[allow(dead_code)]
            impl<T: 'static> __Sp<T> {
                fn new(value: T) -> Self {
                    Self {
                        value,
                        $( $method: ::std::cell::RefCell::new(None), )+
                        every: ::std::cell::RefCell::new(EveryClosures {
                            $( $method: None, )+
                        }),
                        sequence: ::std::cell::RefCell::new(
                            ::std::collections::VecDeque::new()
                        ),
                        executing: ::std::cell::Cell::new(false),
                        calls: ::std::cell::RefCell::new(
                            ::std::collections::HashMap::new()
                        ),
                        expected: ::std::cell::RefCell::new(
                            ::std::collections::HashMap::new()
                        ),
                    }
                }

                fn bump_call(&self, hook: [<$prefix Hook>]) -> usize {
                    let mut calls = self.calls.borrow_mut();
                    let entry = calls.entry(hook.id()).or_insert((hook.name(), 0));
                    let idx = entry.1;
                    entry.1 += 1;
                    idx
                }

                fn set_expected(&self, hook: [<$prefix Hook>], n: usize) {
                    self.expected
                        .borrow_mut()
                        .insert(hook.id(), (hook.name(), n));
                }
            }

            impl<T: 'static> $crate::SyncPoint for __Sp<T> {}

            impl<T: 'static> [<$prefix SyncPoint>] for __Sp<T> {
                $(
                    fn $method(&self $( , $arg: $arg_ty)*) {
                        if self.executing.replace(true) {
                            return;
                        }
                        let __hook = [<$prefix Hook>]::$method;
                        let __idx = self.bump_call(__hook);
                        if $crate::trace_enabled() {
                            eprintln!("[sp] {} call #{}", __hook.name(), __idx + 1);
                        }
                        {
                            let __every = self.every.borrow();
                            if let Some(__f) = &__every.$method {
                                __f(&self.value $( , $arg)*);
                            }
                        }
                        // Sequence: peek the front entry. Three cases:
                        //   * front expects this hook and predicate passes
                        //     (or there is none) -> consume (pop + run).
                        //   * front expects this hook but predicate fails ->
                        //     leave it in place and wait for a fire whose args
                        //     pass; fire-once is NOT triggered (the entry is
                        //     still pending).
                        //   * front expects a different hook -> if a later entry
                        //     matches this hook, panic (ordering violation);
                        //     otherwise fall through to fire-once on first call.
                        let __front_expects_this_hook: bool;
                        let __consume: bool = {
                            let __seq = self.sequence.borrow();
                            match __seq.front() {
                                None => {
                                    __front_expects_this_hook = false;
                                    false
                                }
                                Some(__front) if __front.matches(__hook) => {
                                    __front_expects_this_hook = true;
                                    match __front {
                                        SeqEntry::$method(Some(__pred), _, _) => {
                                            __pred($($arg),*)
                                        }
                                        SeqEntry::$method(None, _, _) => true,
                                        // Unreachable: `matches` already
                                        // confirmed this variant.
                                        _ => true,
                                    }
                                }
                                Some(__front) => {
                                    __front_expects_this_hook = false;
                                    let __has_more =
                                        __seq.iter().any(|e| e.matches(__hook));
                                    if __has_more {
                                        panic!(
                                            "sync point ordering violation: \
                                             expected `{}` next but `{}` fired",
                                            __front.name(),
                                            __hook.name()
                                        );
                                    }
                                    false
                                }
                            }
                        };
                        if __consume {
                            let __entry = self.sequence.borrow_mut().pop_front();
                            if let Some(SeqEntry::$method(_, __f, _)) = __entry {
                                __f(&self.value $( , $arg)*);
                            }
                        } else if !__front_expects_this_hook && __idx == 0 {
                            if let Some(__f) = self.$method.borrow_mut().take() {
                                __f(&self.value $( , $arg)*);
                            }
                        }
                        self.executing.set(false);
                    }
                )+
            }

            // ── Sequence builder ──────────────────────────────────────

            #[allow(dead_code)]
            $vis struct [<$prefix SeqBuilder>]<T: 'static> {
                seq: ::std::collections::VecDeque<SeqEntry<T>>,
            }

            #[allow(dead_code)]
            impl<T: 'static> [<$prefix SeqBuilder>]<T> {
                $(
                    /// Push a sequence entry for this hook.
                    ///
                    /// The entry consumes unconditionally on the next matching
                    /// fire. For a predicate-gated variant see the
                    /// `<$method>_when` builder method.
                    $vis fn $method(
                        &mut self,
                        f: impl FnOnce(&T $( , $arg_ty)*) + 'static,
                    ) -> &mut Self {
                        self.seq
                            .push_back(SeqEntry::$method(None, Box::new(f), false));
                        self
                    }

                    /// Push a predicate-gated sequence entry for this hook.
                    ///
                    /// The entry stays at the front of the sequence until a fire
                    /// of this hook whose arguments pass `pred`, then consumes
                    /// and runs `f`. Fires that fail `pred` leave the entry in
                    /// place. Useful when a hook fires for several distinct
                    /// scenarios (e.g. a real attempt vs. a retry probe) and
                    /// only some should advance the step.
                    ///
                    /// A gated entry must still be consumed: if it is left at
                    /// the front at guard drop, the drop assertion fails. Chain
                    /// [`optional`](Self::optional) if the entry may
                    /// legitimately never fire (e.g. a trailing sentinel).
                    $vis fn [< $method _when >](
                        &mut self,
                        pred: impl Fn($($arg_ty),*) -> bool + 'static,
                        f: impl FnOnce(&T $( , $arg_ty)*) + 'static,
                    ) -> &mut Self {
                        self.seq.push_back(SeqEntry::$method(
                            Some(Box::new(pred)),
                            Box::new(f),
                            false,
                        ));
                        self
                    }
                )+

                /// Mark the most recently pushed entry as optional: it may
                /// legitimately remain unconsumed at guard drop (its hook
                /// never fired, or its predicate never passed). Typical use
                /// is a trailing sentinel that must panic only on an
                /// unexpected extra fire.
                ///
                /// Panics if no entries have been pushed yet.
                $vis fn optional(&mut self) -> &mut Self {
                    self.seq
                        .back_mut()
                        .expect("SeqBuilder::optional called with no entries")
                        .set_optional(true);
                    self
                }
            }

            // ── Every builder ─────────────────────────────────────────

            #[allow(dead_code)]
            $vis struct EveryBuilder<T: 'static> {
                every: EveryClosures<T>,
            }

            #[allow(dead_code)]
            impl<T: 'static> EveryBuilder<T> {
                $(
                    /// Register a closure that fires on every invocation of this hook.
                    $vis fn $method(&mut self, f: impl Fn(&T $( , $arg_ty)*) + 'static) -> &mut Self {
                        self.every.$method = Some(Box::new(f));
                        self
                    }
                )+
            }

            // ── Fire-once fluent helper ───────────────────────────────

            #[allow(dead_code)]
            $vis struct SpExpect<'a, T: 'static> {
                sp: &'a __Sp<T>,
                hook: [<$prefix Hook>],
            }

            #[allow(dead_code)]
            impl<T: 'static> SpExpect<'_, T> {
                /// Assert that the hook fires exactly `n` times.
                $vis fn expect(self, n: usize) {
                    self.sp.set_expected(self.hook, n);
                }
            }

            // ── Guard ─────────────────────────────────────────────────

            /// Guard returned by `{$prefix}Sp::install_guard()`.
            ///
            /// Derefs to the guarded value. Drop asserts that all registered
            /// sequences were consumed and all `expect_calls` counts match.
            #[clippy::has_significant_drop]
            #[must_use]
            $vis struct [<$prefix SpGuard>]<T: 'static> {
                sp: &'static __Sp<T>,
                old: &'static dyn [<$prefix SyncPoint>],
                installed_at: &'static std::panic::Location<'static>,
            }

            #[allow(dead_code)]
            impl<T: 'static> [<$prefix SpGuard>]<T> {
                #[track_caller]
                fn install(value: T) -> Self {
                    let sp: &'static __Sp<T> = Box::leak(Box::new(__Sp::new(value)));
                    let old = __SP_TL.with(|__c| __c.replace(sp));
                    Self {
                        sp,
                        old,
                        installed_at: std::panic::Location::caller(),
                    }
                }

                $(
                    /// Register a fire-once closure for this hook.
                    ///
                    /// The closure runs on the first invocation. Chain
                    /// `.expect(n)` to assert a specific call count, or drop
                    /// the return for an unconditional one-shot.
                    $vis fn $method(
                        &self,
                        f: impl FnOnce(&T $( , $arg_ty)*) + 'static,
                    ) -> SpExpect<'_, T> {
                        *self.sp.$method.borrow_mut() = Some(Box::new(f));
                        SpExpect {
                            sp: self.sp,
                            hook: [<$prefix Hook>]::$method,
                        }
                    }
                )+

                /// Register an ordered sequence of hook fires.
                ///
                /// Each builder method pushes a closure that must fire in
                /// registration order. Out-of-order fires panic.
                $vis fn sequence(&self, f: impl FnOnce(&mut [<$prefix SeqBuilder>]<T>)) {
                    let mut builder = [<$prefix SeqBuilder>] {
                        seq: ::std::collections::VecDeque::new(),
                    };
                    f(&mut builder);
                    *self.sp.sequence.borrow_mut() = builder.seq;
                }

                /// Register closures that fire on every invocation.
                $vis fn every(&self, f: impl FnOnce(&mut EveryBuilder<T>)) {
                    let mut builder = EveryBuilder {
                        every: EveryClosures {
                            $( $method: None, )+
                        },
                    };
                    f(&mut builder);
                    *self.sp.every.borrow_mut() = builder.every;
                }

                /// Assert that `hook` fires exactly `n` times before drop.
                $vis fn expect_calls(&self, hook: [<$prefix Hook>], n: usize) {
                    self.sp.set_expected(hook, n);
                }
            }

            impl<T: 'static> std::ops::Deref for [<$prefix SpGuard>]<T> {
                type Target = T;
                fn deref(&self) -> &T {
                    &self.sp.value
                }
            }

            impl<T: 'static> Drop for [<$prefix SpGuard>]<T> {
                fn drop(&mut self) {
                    __SP_TL.with(|__c| __c.set(self.old));

                    let seq = self.sp.sequence.borrow();
                    // Entries marked optional via `SeqBuilder::optional`
                    // (e.g. a trailing sentinel) may remain unconsumed:
                    // their hook never fired, or their predicate never
                    // passed. Every other entry — gated or not — must have
                    // fired; any remaining is a missing scenario step.
                    let unconsumed: Vec<_> =
                        seq.iter().filter(|e| !e.is_optional()).collect();
                    assert!(
                        unconsumed.is_empty(),
                        "sync point sequence not fully consumed: \
                         {} entr{} remaining [{}] (installed at {})",
                        unconsumed.len(),
                        if unconsumed.len() == 1 { "y" } else { "ies" },
                        unconsumed
                            .iter()
                            .map(|e| e.name())
                            .collect::<Vec<_>>()
                            .join(", "),
                        self.installed_at,
                    );
                    drop(seq);

                    let expected = self.sp.expected.borrow();
                    let calls = self.sp.calls.borrow();
                    for (id, (name, expected)) in expected.iter() {
                        let actual = calls.get(id).map_or(0, |(_, c)| *c);
                        assert_eq!(
                            actual, *expected,
                            "sync point hook `{name}` fired {actual} \
                             time(s), expected {expected} (installed at {})",
                            self.installed_at,
                        );
                    }
                }
            }
        }
    };
}
